### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by macobo** [PostHog/bigquery-plugin#3]
There was a type error in sentry: https://sentry.io/organizations/posthog/issues/2203245089/?project=5592816&query=is%3Aunassigned+is%3Aunresolved

Message:
```
[___4] 🔔 TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received type boolean (true)
    at Function.byteLength (buffer.js:728:11)
    at BufferWriter.write_string_buffer [as string] (/code/plugins/node_modules/protobufjs/src/writer_buffer.js:70:27)
    at Function.encode (/code/plugins/node_modules/@posthog/plugin-server/dist/idl/protos.js:48:31)
    at Function.encodeDelimited (/code/plugins/node_modules/@posthog/plugin-server/dist/idl/protos.js:65:21)
    at EventsProcessor.createEvent (/code/plugins/node_modules/@posthog/plugin-server/dist/ingestion/process-event.js:346:47)
    at EventsProcessor.captureEE (/code/plugins/node_modules/@posthog/plugin-server/dist/ingestion/process-event.js:251:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EventsProcessor.processEvent (/code/plugins/node_modules/@posthog/plugin-server/dist/ingestion/process-event.js:81:22)
    at async Object.ingestEvent (/code/plugins/node_modules/@posthog/plugin-server/dist/ingestion/ingest-event.js:33:9)
    at async /code/plugins/node_modules/@posthog/plugin-server/dist/worker/worker.js:40:40
    at async /code/plugins/node_modules/@posthog/piscina/dist/src/worker.js:141:26 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by macobo** [comment]
Oops, wrong repo
